version: '3.7'

services:
  portal:
    build:
      context: .
      dockerfile: Dockerfile
    image: portal_image
    container_name: portal
    restart: unless-stopped
    tty: true
    cap_add:
      - NET_ADMIN
    volumes:
      - ./local.ini:/usr/local/etc/php/conf.d/local.ini
      - /storage/portal:/var/www/portal/storage/app
    networks:
      - intra_net

networks:
  intra_net:
    name: internal_network
